// Package k8s is the Kubernetes manifest backend.
//
// Emits a hardened Deployment + Service + NetworkPolicy + ServiceAccount that
// mirrors the reference patterns in /k8s/deployment.yaml: non-root UID 10001,
// readOnlyRootFilesystem, drop ALL caps, NetworkPolicy egress to NATS +
// Postgres only.
package k8s

import (
	"bytes"
	"text/template"

	"github.com/vibeguard/vibeguard/internal/ir"
	"github.com/vibeguard/vibeguard/internal/render"
)

// Backend implements render.Backend for Kubernetes manifests.
type Backend struct {
	Image string
	Tag   string
}

// New constructs a K8s backend.
func New(image, tag string) *Backend {
	if image == "" {
		image = "ghcr.io/example/app"
	}
	if tag == "" {
		tag = "latest"
	}
	return &Backend{Image: image, Tag: tag}
}

// Name reports "k8s".
func (Backend) Name() string { return "k8s" }

// Plan emits Deployment, Service, NetworkPolicy.
func (b *Backend) Plan(app *ir.Application) (render.FileSet, error) {
	tmpl := template.Must(template.New("k8s").Parse(manifestTmpl))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		Name  string
		Image string
		Tag   string
	}{
		Name:  app.Metadata.Name,
		Image: b.Image,
		Tag:   b.Tag,
	}); err != nil {
		return nil, err
	}
	return render.FileSet{
		{
			Path:    "k8s/deployment.yaml",
			Mode:    0o644,
			Content: buf.Bytes(),
		},
	}, nil
}

const manifestTmpl = `# Generated by vibeguard. To re-emit run: vibeguard generate -f vibeguard.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Name}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      serviceAccountName: {{.Name}}
      containers:
        - name: app
          image: {{.Image}}:{{.Tag}}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{.Name}}-secrets
                  key: database-url
            - name: NATS_URL
              value: "nats://nats:4222"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "512Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
spec:
  selector:
    app: {{.Name}}
  ports:
    - port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Name}}
spec:
  podSelector:
    matchLabels:
      app: {{.Name}}
  policyTypes: [Ingress, Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: nats
      ports:
        - port: 4222
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - port: 5432
          protocol: TCP
    - ports:
        - port: 53
          protocol: UDP
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
`
