// Package sql is the SQL/DDL backend for the vibeguard render engine.
//
// It emits one migration file containing CREATE TABLE statements, indexes,
// soft-delete columns, and CREATE POLICY statements derived from the
// declaration's policies.row_level_security blocks. The output is compatible
// with golang-migrate (numbered .up.sql / .down.sql files).
package sql

import (
	"fmt"
	"sort"
	"strings"

	"github.com/vibeguard/vibeguard/internal/ir"
	"github.com/vibeguard/vibeguard/internal/render"
)

// Backend implements render.Backend for SQL DDL output.
type Backend struct{}

// New constructs a SQL backend.
func New() *Backend { return &Backend{} }

// Name reports "sql".
func (Backend) Name() string { return "sql" }

// Plan emits the migration files for the application.
func (Backend) Plan(app *ir.Application) (render.FileSet, error) {
	var up strings.Builder
	var down strings.Builder
	up.WriteString("-- Generated by vibeguard. To re-emit run: vibeguard generate -f vibeguard.yaml\n\n")
	down.WriteString("-- Generated by vibeguard.\n\n")

	if app.Global.MultiTenancy.Enabled {
		up.WriteString("-- Multi-tenancy enabled (isolation: " + app.Global.MultiTenancy.Isolation + "). RLS policies fire on app.tenant_id session variable.\n\n")
	}

	for _, mod := range app.Modules {
		for _, ent := range mod.Entities {
			emitTable(&up, &down, ent)
		}
		for _, p := range mod.Policies.RowLevelSecurity {
			emitRLS(&up, p, findEntityTable(app, p.Entity))
		}
	}
	emitParentFKs(&up, app)

	return render.FileSet{
		{
			Path:    "migrations/0001_init.up.sql",
			Mode:    0o644,
			Content: []byte(up.String()),
		},
		{
			Path:    "migrations/0001_init.down.sql",
			Mode:    0o644,
			Content: []byte(down.String()),
		},
	}, nil
}

func findEntityTable(app *ir.Application, name string) string {
	for _, mod := range app.Modules {
		for _, ent := range mod.Entities {
			if ent.Name == name {
				return ent.Table
			}
		}
	}
	return strings.ToLower(name)
}

func emitTable(up, down *strings.Builder, ent *ir.Entity) {
	fmt.Fprintf(up, "-- entity %s (sensitivity: %s)\n", ent.Name, ent.Sensitivity)
	fmt.Fprintf(up, "CREATE TABLE IF NOT EXISTS %s (\n", ent.Table)
	cols := make([]string, 0, len(ent.Fields)+1)
	for _, f := range ent.Fields {
		cols = append(cols, "    "+colDef(f))
	}
	if ent.SoftDelete {
		cols = append(cols, "    deleted_at timestamptz")
	}
	if ent.PrimaryKey != nil {
		cols = append(cols, "    PRIMARY KEY ("+ent.PrimaryKey.Name+")")
	}
	up.WriteString(strings.Join(cols, ",\n"))
	up.WriteString("\n);\n")

	for _, f := range ent.Fields {
		if f.DBHints.Index {
			fmt.Fprintf(up, "CREATE INDEX IF NOT EXISTS %s_%s_idx ON %s(%s);\n", ent.Table, f.Name, ent.Table, f.Name)
		}
	}
	up.WriteString("\n")

	fmt.Fprintf(down, "DROP TABLE IF EXISTS %s;\n", ent.Table)
}

// emitParentFKs adds a FOREIGN KEY ... ON DELETE CASCADE for each parent
// edge. The expected FK column is "<parent_table_singular>_id"; if no such
// column exists on the child it is skipped silently (declarations may pre-
// declare relationships with a custom foreign_key — those still emit via
// the existing relationships path in future renderer work).
func emitParentFKs(up *strings.Builder, app *ir.Application) {
	for _, mod := range app.Modules {
		for _, ent := range mod.Entities {
			if len(ent.ParentRefs) == 0 {
				continue
			}
			for _, p := range ent.ParentRefs {
				fkCol := singular(p.Table) + "_id"
				if !entityHasField(ent, fkCol) {
					continue
				}
				constraint := ent.Table + "_" + fkCol + "_fkey"
				fmt.Fprintf(up, "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s(%s) ON DELETE CASCADE;\n",
					ent.Table, constraint, fkCol, p.Table, parentPK(p))
			}
		}
	}
}

func entityHasField(ent *ir.Entity, name string) bool {
	for _, f := range ent.Fields {
		if f.Name == name {
			return true
		}
	}
	return false
}

func parentPK(p *ir.Entity) string {
	if p.PrimaryKey != nil {
		return p.PrimaryKey.Name
	}
	return "id"
}

func singular(s string) string {
	switch {
	case strings.HasSuffix(s, "ies"):
		return s[:len(s)-3] + "y"
	case strings.HasSuffix(s, "ses"), strings.HasSuffix(s, "xes"), strings.HasSuffix(s, "zes"):
		return s[:len(s)-2]
	case strings.HasSuffix(s, "s"):
		return s[:len(s)-1]
	}
	return s
}

func emitRLS(up *strings.Builder, p ir.RLSPolicy, table string) {
	cond := strings.NewReplacer(
		"{tenant_id}", "current_setting('app.tenant_id', true)::uuid",
		"{user_id}", "current_setting('app.user_id', true)::uuid",
		"{role}", "current_setting('app.role', true)",
	).Replace(p.Condition)
	policyName := table + "_tenant_isolation"
	fmt.Fprintf(up, "ALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n", table)
	fmt.Fprintf(up, "CREATE POLICY %s ON %s\n    USING (%s);\n\n", policyName, table, cond)
	_ = sort.Search
}

func colDef(f *ir.Field) string {
	col := f.Name + " " + sqlType(f)
	if f.Unique {
		col += " UNIQUE"
	}
	if !f.Nullable && !f.Primary {
		col += " NOT NULL"
	}
	if f.Default != nil {
		col += " DEFAULT " + sqlDefault(f, *f.Default)
	}
	return col
}

func sqlType(f *ir.Field) string {
	switch f.Type {
	case ir.FieldString:
		return "text"
	case ir.FieldText:
		return "text"
	case ir.FieldInt:
		return "integer"
	case ir.FieldBigInt:
		return "bigint"
	case ir.FieldBool:
		return "boolean"
	case ir.FieldUUID:
		return "uuid"
	case ir.FieldTimestamp:
		return "timestamptz"
	case ir.FieldEnum:
		return "text"
	case ir.FieldJSON:
		return "jsonb"
	case ir.FieldDecimal:
		return "numeric"
	}
	return "text"
}

func sqlDefault(f *ir.Field, val string) string {
	switch f.Type {
	case ir.FieldString, ir.FieldText, ir.FieldEnum:
		return "'" + strings.ReplaceAll(val, "'", "''") + "'"
	case ir.FieldBool, ir.FieldInt, ir.FieldBigInt, ir.FieldDecimal:
		return val
	case ir.FieldTimestamp:
		if val == "now" || val == "now()" {
			return "now()"
		}
		return "'" + val + "'"
	}
	return "'" + val + "'"
}
