// Package golang is the Go-source backend for the vibeguard render engine.
//
// It emits, per declared application:
//
//   - go.mod (module declaration with platform SDK pinned)
//   - cmd/server/main.go (process bootstrap: db + events + router + signals)
//   - internal/<module>/<entity>.go (domain types)
//   - internal/<module>/<entity>_repository.go (parameterized SQL with
//     field-whitelisted UPDATEs and tenant filtering)
//   - internal/<module>/<entity>_handler.go (thin HTTP handlers — only the
//     verbs the declaration enabled)
//   - internal/<module>/routes.go (route registrar; only registers routes for
//     enabled CRUD verbs — defense in depth alongside the repository)
//
// All emitted files carry a "Code generated by vibeguard" banner and run
// through gofmt before write.
package golang

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/vibeguard/vibeguard/internal/ir"
	"github.com/vibeguard/vibeguard/internal/render"
)

// Backend implements render.Backend for Go source output.
type Backend struct {
	ModulePath   string // e.g. "github.com/example/team-task-saas"
	PlatformPath string // filesystem path to the platform module; when set, a replace directive is emitted
}

// New constructs a Go backend rooted at modulePath.
func New(modulePath string) *Backend {
	if modulePath == "" {
		modulePath = "github.com/example/app"
	}
	return &Backend{ModulePath: modulePath}
}

// Name reports "go".
func (Backend) Name() string { return "go" }

// Plan emits the Go file set for app.
func (b *Backend) Plan(app *ir.Application) (render.FileSet, error) {
	var fs render.FileSet

	mainFile, err := b.emitMain(app)
	if err != nil {
		return nil, err
	}
	fs = append(fs, mainFile)

	gomod := b.emitGoMod(app)
	fs = append(fs, gomod)

	for _, mod := range app.Modules {
		for _, ent := range mod.Entities {
			files, err := b.emitEntity(app, mod, ent)
			if err != nil {
				return nil, err
			}
			fs = append(fs, files...)
		}
	}
	return fs, nil
}

const headerLine = "// Code generated by vibeguard; DO NOT EDIT."

func (b *Backend) emitMain(app *ir.Application) (render.FileSpec, error) {
	tmpl := template.Must(template.New("main").Funcs(funcMap).Parse(mainTmpl))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		ModulePath string
		App        *ir.Application
	}{b.ModulePath, app}); err != nil {
		return render.FileSpec{}, err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return render.FileSpec{}, fmt.Errorf("format main.go: %w\n%s", err, buf.String())
	}
	return render.FileSpec{
		Path:    "cmd/server/main.go",
		Mode:    0o644,
		Content: src,
		Header:  headerLine,
	}, nil
}

func (b *Backend) emitGoMod(app *ir.Application) render.FileSpec {
	replace := ""
	if b.PlatformPath != "" {
		replace = "\nreplace github.com/vibeguard/platform => " + b.PlatformPath + "\n"
	}
	mod := fmt.Sprintf(`module %s

go 1.23

require (
	github.com/gin-gonic/gin v1.10.0
	github.com/google/uuid v1.6.0
	github.com/vibeguard/platform v0.0.0
	go.uber.org/zap v1.27.0
)
%s`, b.ModulePath, replace)
	return render.FileSpec{
		Path:    "go.mod",
		Mode:    0o644,
		Content: []byte(mod),
	}
}

func (b *Backend) emitEntity(app *ir.Application, mod ir.Module, ent *ir.Entity) (render.FileSet, error) {
	var fs render.FileSet
	pkg := goPackageName(mod.Name)
	dir := "internal/" + pkg

	// Domain
	if file, err := b.emitDomain(app, mod, ent, pkg, dir); err == nil {
		fs = append(fs, file)
	} else {
		return nil, err
	}
	// Repository
	if file, err := b.emitRepository(app, mod, ent, pkg, dir); err == nil {
		fs = append(fs, file)
	} else {
		return nil, err
	}
	// Handler
	if file, err := b.emitHandler(app, mod, ent, pkg, dir); err == nil {
		fs = append(fs, file)
	} else {
		return nil, err
	}
	// Node-backed custom endpoints (wrapper + nodes/ stubs).
	if extra, err := b.emitNodes(app, mod, ent, pkg, dir); err == nil {
		fs = append(fs, extra...)
	} else {
		return nil, err
	}
	return fs, nil
}

func (b *Backend) emitDomain(app *ir.Application, mod ir.Module, ent *ir.Entity, pkg, dir string) (render.FileSpec, error) {
	tmpl := template.Must(template.New("domain").Funcs(funcMap).Parse(domainTmpl))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		Pkg    string
		Entity *ir.Entity
	}{pkg, ent}); err != nil {
		return render.FileSpec{}, err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return render.FileSpec{}, fmt.Errorf("format %s domain: %w\n%s", ent.Name, err, buf.String())
	}
	return render.FileSpec{
		Path:    dir + "/" + snake(ent.Name) + ".go",
		Mode:    0o644,
		Content: src,
		Header:  headerLine,
	}, nil
}

func (b *Backend) emitRepository(app *ir.Application, mod ir.Module, ent *ir.Entity, pkg, dir string) (render.FileSpec, error) {
	tmpl := template.Must(template.New("repo").Funcs(funcMap).Parse(repoTmpl))
	var buf bytes.Buffer

	insertable := make([]*ir.Field, 0, len(ent.Fields))
	for _, f := range ent.Fields {
		if !f.Primary {
			insertable = append(insertable, f)
		}
	}
	insertCols := joinFieldNames(insertable)
	insertPlaceholders := placeholders(len(insertable))
	allCols := joinFieldNames(ent.Fields)

	if err := tmpl.Execute(&buf, struct {
		Pkg                string
		Entity             *ir.Entity
		MultiTenant        bool
		TenantField        string
		Insertable         []*ir.Field
		InsertCols         string
		InsertPlaceholders string
		AllCols            string
	}{
		Pkg:                pkg,
		Entity:             ent,
		MultiTenant:        app.Global.MultiTenancy.Enabled,
		TenantField:        tenantField(app),
		Insertable:         insertable,
		InsertCols:         insertCols,
		InsertPlaceholders: insertPlaceholders,
		AllCols:            allCols,
	}); err != nil {
		return render.FileSpec{}, err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return render.FileSpec{}, fmt.Errorf("format %s repo: %w\n%s", ent.Name, err, buf.String())
	}
	return render.FileSpec{
		Path:    dir + "/" + snake(ent.Name) + "_repository.go",
		Mode:    0o644,
		Content: src,
		Header:  headerLine,
	}, nil
}

func (b *Backend) emitHandler(app *ir.Application, mod ir.Module, ent *ir.Entity, pkg, dir string) (render.FileSpec, error) {
	tmpl := template.Must(template.New("handler").Funcs(funcMap).Parse(handlerTmpl))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		Pkg    string
		Entity *ir.Entity
	}{pkg, ent}); err != nil {
		return render.FileSpec{}, err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return render.FileSpec{}, fmt.Errorf("format %s handler: %w\n%s", ent.Name, err, buf.String())
	}
	return render.FileSpec{
		Path:    dir + "/" + snake(ent.Name) + "_handler.go",
		Mode:    0o644,
		Content: src,
		Header:  headerLine,
	}, nil
}

// ---------- helpers ----------

func tenantField(app *ir.Application) string {
	if app.Global.MultiTenancy.TenantIDField != "" {
		return app.Global.MultiTenancy.TenantIDField
	}
	return "tenant_id"
}

func goPackageName(s string) string {
	return strings.ToLower(strings.ReplaceAll(s, "-", ""))
}

func snake(s string) string {
	var out []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			out = append(out, '_')
		}
		if r >= 'A' && r <= 'Z' {
			out = append(out, r-'A'+'a')
		} else {
			out = append(out, r)
		}
	}
	return string(out)
}

func goType(f *ir.Field) string {
	switch f.Type {
	case ir.FieldString, ir.FieldText, ir.FieldEnum:
		return "string"
	case ir.FieldInt:
		return "int"
	case ir.FieldBigInt:
		return "int64"
	case ir.FieldBool:
		return "bool"
	case ir.FieldUUID:
		return "string"
	case ir.FieldTimestamp:
		return "time.Time"
	case ir.FieldJSON:
		return "json.RawMessage"
	case ir.FieldDecimal:
		return "string"
	}
	return "string"
}

func goField(f *ir.Field) string {
	t := goType(f)
	if f.Nullable {
		return "*" + t
	}
	return t
}

func goName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func entityImportsTime(ent *ir.Entity) bool {
	for _, f := range ent.Fields {
		if f.Type == ir.FieldTimestamp {
			return true
		}
	}
	return ent.SoftDelete
}

func entityImportsJSON(ent *ir.Entity) bool {
	for _, f := range ent.Fields {
		if f.Type == ir.FieldJSON {
			return true
		}
	}
	return false
}

func joinFieldNames(fs []*ir.Field) string {
	out := ""
	for i, f := range fs {
		if i > 0 {
			out += ", "
		}
		out += f.Name
	}
	return out
}

func placeholders(n int) string {
	out := ""
	for i := 1; i <= n; i++ {
		if i > 1 {
			out += ", "
		}
		out += "$" + itoa(i)
	}
	return out
}

func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	var buf []byte
	for i > 0 {
		buf = append([]byte{byte('0' + i%10)}, buf...)
		i /= 10
	}
	return string(buf)
}

var funcMap = template.FuncMap{
	"goField":           goField,
	"goName":            goName,
	"goType":            goType,
	"snake":             snake,
	"lower":             strings.ToLower,
	"goPkg":             goPackageName,
	"add1":              func(i int) int { return i + 1 },
	"hasCreate":         func(c ir.CRUD) bool { return c.Create },
	"hasRead":           func(c ir.CRUD) bool { return c.Read },
	"hasList":           func(c ir.CRUD) bool { return c.List },
	"hasUpdate":         func(c ir.CRUD) bool { return len(c.UpdateFields) > 0 },
	"hasDelete":         func(c ir.CRUD) bool { return c.Delete },
	"entityImportsTime": entityImportsTime,
	"entityImportsJSON": entityImportsJSON,
	"ginVerb":           ginVerb,
	"hasNodeEndpoints":  hasNodeEndpoints,
	"anyNodeEndpoints":  anyNodeEndpoints,
}

// hasNodeEndpoints reports whether ent has any custom_endpoint with a Node ref.
func hasNodeEndpoints(ent *ir.Entity) bool {
	for _, ep := range ent.API.CustomEndpoints {
		if strings.TrimSpace(ep.Node) != "" {
			return true
		}
	}
	return false
}

// anyNodeEndpoints reports whether the application contains any node-backed
// custom endpoint at all. Used by main.go to gate the llm gateway import +
// variable declaration so apps without nodes don't pull in the llm package.
func anyNodeEndpoints(app *ir.Application) bool {
	for _, mod := range app.Modules {
		for _, ent := range mod.Entities {
			if hasNodeEndpoints(ent) {
				return true
			}
		}
	}
	return false
}

// ginVerb maps an HTTP method to gin's IRouter verb method name.
func ginVerb(method string) string {
	switch strings.ToUpper(method) {
	case "GET":
		return "GET"
	case "POST":
		return "POST"
	case "PUT":
		return "PUT"
	case "PATCH":
		return "PATCH"
	case "DELETE":
		return "DELETE"
	case "HEAD":
		return "HEAD"
	case "OPTIONS":
		return "OPTIONS"
	}
	return "POST"
}
