package golang

// Templates are kept inline (rather than embed.FS) so contributors can read
// the generator and the generated shape side by side.

const mainTmpl = `package main

import (
	"context"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/vibeguard/platform/db"
	dbpg "github.com/vibeguard/platform/db/postgres"
	"github.com/vibeguard/platform/events"
	evjs "github.com/vibeguard/platform/events/jetstream"
{{- if anyNodeEndpoints .App }}
	"github.com/vibeguard/platform/llm"
{{- end }}

{{- range .App.Modules }}{{- range .Entities }}
	"{{$.ModulePath}}/internal/{{goPkg .Module.Name}}"
{{- end }}{{- end }}
)

// main wires the platform SDK and registers routes derived from the
// declaration. Generated by vibeguard.
func main() {
	logger, _ := zap.NewProduction()
	defer logger.Sync()

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	pgURL := os.Getenv("DATABASE_URL")
	if pgURL == "" {
		logger.Fatal("DATABASE_URL not set")
	}
	database, err := dbpg.New(ctx, pgURL)
	if err != nil {
		logger.Fatal("postgres", zap.Error(err))
	}
	defer database.Close()

	natsURL := os.Getenv("NATS_URL")
	if natsURL == "" {
		natsURL = "nats://localhost:4222"
	}
	bus, err := evjs.New(natsURL, logger)
	if err != nil {
		logger.Fatal("nats jetstream", zap.Error(err))
	}
	defer bus.Close()

	router := gin.New()
	router.Use(gin.Recovery())
	router.Use(requestIDMiddleware())
	router.Use(tenantContextMiddleware())

{{- if anyNodeEndpoints .App }}
	// llmGateway is wired into node handlers as part of Deps. Apps that don't
	// declare an llm provider can leave this nil — nodes nil-check d.LLM.
	var llmGateway llm.Gateway
{{- end }}

{{- range .App.Modules }}{{- range .Entities }}
	{{snake .Name}}Repo := {{goPkg .Module.Name}}.New{{goName .Name}}Repository(database)
	{{snake .Name}}Handler := {{goPkg .Module.Name}}.New{{goName .Name}}Handler({{snake .Name}}Repo, bus)
	{{goPkg .Module.Name}}.Register{{goName .Name}}Routes(router, {{snake .Name}}Handler)
{{- if hasNodeEndpoints . }}
	{{snake .Name}}NodeHandler := {{goPkg .Module.Name}}.New{{goName .Name}}NodeHandler(database, bus, llmGateway, logger)
	{{goPkg .Module.Name}}.Register{{goName .Name}}NodeRoutes(router, {{snake .Name}}NodeHandler)
{{- end }}
{{- end }}{{- end }}

	srv := &http.Server{Addr: ":8080", Handler: router, ReadHeaderTimeout: 5 * time.Second}
	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Fatal("listen", zap.Error(err))
		}
	}()
	logger.Info("listening on :8080")
	<-ctx.Done()
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	_ = srv.Shutdown(shutdownCtx)

	_ = database
	_ = bus
	_ = events.Event{}
	_ = db.RequestContext{}
}

// requestIDMiddleware tags each request with an X-Request-Id header echoed
// back to the client. Generated by vibeguard.
func requestIDMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		id := c.GetHeader("X-Request-Id")
		if id == "" {
			id = randomID()
		}
		c.Set("request_id", id)
		c.Header("X-Request-Id", id)
		c.Next()
	}
}

// tenantContextMiddleware extracts the tenant from headers and installs it on
// the request context so platform/db drivers bind it to Postgres session
// settings (RLS). In production this is replaced by the auth middleware that
// validates a JWT and pulls tenant_id from claims.
func tenantContextMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		rc := db.RequestContext{
			TenantID: c.GetHeader("X-Tenant-Id"),
			UserID:   c.GetHeader("X-User-Id"),
			Role:     c.GetHeader("X-User-Role"),
		}
		ctx := db.WithRequest(c.Request.Context(), rc)
		c.Request = c.Request.WithContext(ctx)
		c.Next()
	}
}

func randomID() string {
	const alphabet = "0123456789abcdef"
	b := make([]byte, 16)
	for i := range b {
		b[i] = alphabet[time.Now().UnixNano()%int64(len(alphabet))]
	}
	return string(b)
}
`

const domainTmpl = `package {{.Pkg}}

{{- if entityImportsTime .Entity }}
import "time"
{{- end }}
{{- if entityImportsJSON .Entity }}
import "encoding/json"
{{- end }}

// {{goName .Entity.Name}} is the {{.Entity.Name}} entity (table: {{.Entity.Table}}).
// Sensitivity: {{.Entity.Sensitivity}}.
type {{goName .Entity.Name}} struct {
{{- range .Entity.Fields }}
	{{goName .Name}} {{goField .}} ` + "`json:\"{{.Name}}{{if .Nullable}},omitempty{{end}}\"`" + `
{{- end }}
{{- if .Entity.SoftDelete }}
	DeletedAt *time.Time ` + "`json:\"deleted_at,omitempty\"`" + `
{{- end }}
}
{{- if hasCreate .Entity.CRUD }}

// {{goName .Entity.Name}}CreateRequest is the request body for POST {{.Entity.API.BasePath}}.
type {{goName .Entity.Name}}CreateRequest struct {
{{- range .Entity.Fields }}
{{- if not .Primary }}
	{{goName .Name}} {{goType .}} ` + "`json:\"{{.Name}}\"`" + `
{{- end }}
{{- end }}
}
{{- end }}
{{- if hasUpdate .Entity.CRUD }}

// {{goName .Entity.Name}}UpdateRequest is the request body for PATCH {{.Entity.API.BasePath}}/:id.
// Field whitelist enforced by the declaration's crud.update list.
type {{goName .Entity.Name}}UpdateRequest struct {
{{- range .Entity.CRUD.UpdateFields }}
	{{goName .Name}} *{{goType .}} ` + "`json:\"{{.Name}},omitempty\"`" + `
{{- end }}
}
{{- end }}
`

const repoTmpl = `package {{.Pkg}}

import (
	"context"
	"errors"
{{- if or (hasCreate .Entity.CRUD) (hasList .Entity.CRUD) (hasUpdate .Entity.CRUD) }}
	"fmt"
{{- end }}
{{- if hasUpdate .Entity.CRUD }}
	"strings"
{{- end }}

	"github.com/vibeguard/platform/db"
)

// {{goName .Entity.Name}}Repository wraps platform/db with parameterized SQL
// derived from the declaration. The Update path enforces a field whitelist —
// no field outside crud.update can be touched, even by a misuse of the API.
type {{goName .Entity.Name}}Repository struct {
	db db.DB
}

// New{{goName .Entity.Name}}Repository constructs a repository.
func New{{goName .Entity.Name}}Repository(database db.DB) *{{goName .Entity.Name}}Repository {
	return &{{goName .Entity.Name}}Repository{db: database}
}

// ErrNotFound is returned when a single-row lookup misses.
var ErrNotFound = errors.New("not found")

{{ if hasCreate .Entity.CRUD }}
// Create inserts a {{.Entity.Name}}.
func (r *{{goName .Entity.Name}}Repository) Create(ctx context.Context, in {{goName .Entity.Name}}CreateRequest) (*{{goName .Entity.Name}}, error) {
	const q = ` + "`INSERT INTO {{.Entity.Table}} ({{.InsertCols}}) VALUES ({{.InsertPlaceholders}}) RETURNING {{.AllCols}}`" + `
	row := r.db.QueryRow(ctx, q,
{{- range .Insertable }}
		in.{{goName .Name}},
{{- end }}
	)
	var out {{goName .Entity.Name}}
	if err := row.Scan({{ range $i, $f := .Entity.Fields }}{{ if $i }}, {{ end }}&out.{{goName $f.Name}}{{- end }}); err != nil {
		return nil, fmt.Errorf("create {{.Entity.Name}}: %w", err)
	}
	return &out, nil
}
{{ end }}

{{ if hasRead .Entity.CRUD }}
// Get loads one row by id. Tenant filtering is enforced by Postgres RLS via
// the session settings the driver installs on connection checkout.
func (r *{{goName .Entity.Name}}Repository) Get(ctx context.Context, id string) (*{{goName .Entity.Name}}, error) {
	const q = ` + "`SELECT {{.AllCols}} FROM {{.Entity.Table}} WHERE {{.Entity.PrimaryKey.Name}} = $1{{ if .Entity.SoftDelete }} AND deleted_at IS NULL{{ end }}`" + `
	row := r.db.QueryRow(ctx, q, id)
	var out {{goName .Entity.Name}}
	if err := row.Scan({{ range $i, $f := .Entity.Fields }}{{ if $i }}, {{ end }}&out.{{goName $f.Name}}{{- end }}); err != nil {
		return nil, ErrNotFound
	}
	return &out, nil
}
{{ end }}

{{ if hasList .Entity.CRUD }}
// List loads many rows. Tenant filtering is enforced by Postgres RLS.
func (r *{{goName .Entity.Name}}Repository) List(ctx context.Context, limit int) ([]{{goName .Entity.Name}}, error) {
	const q = ` + "`SELECT {{.AllCols}} FROM {{.Entity.Table}}{{ if .Entity.SoftDelete }} WHERE deleted_at IS NULL{{ end }} LIMIT $1`" + `
	rows, err := r.db.Query(ctx, q, limit)
	if err != nil {
		return nil, fmt.Errorf("list {{.Entity.Name}}: %w", err)
	}
	defer rows.Close()
	var out []{{goName .Entity.Name}}
	for rows.Next() {
		var v {{goName .Entity.Name}}
		if err := rows.Scan({{ range $i, $f := .Entity.Fields }}{{ if $i }}, {{ end }}&v.{{goName $f.Name}}{{- end }}); err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}
{{ end }}

{{ if hasUpdate .Entity.CRUD }}
// Update applies a partial update. The set of acceptable columns is locked at
// generation time to the declaration's crud.update whitelist; an unknown field
// is impossible to construct because the request struct only has those fields.
func (r *{{goName .Entity.Name}}Repository) Update(ctx context.Context, id string, in {{goName .Entity.Name}}UpdateRequest) (*{{goName .Entity.Name}}, error) {
	var sets []string
	var args []any
{{- range $i, $f := .Entity.CRUD.UpdateFields }}
	if in.{{goName $f.Name}} != nil {
		sets = append(sets, fmt.Sprintf("{{$f.Name}} = $%d", len(args)+1))
		args = append(args, *in.{{goName $f.Name}})
	}
{{- end }}
	if len(sets) == 0 {
		return r.Get(ctx, id)
	}
	args = append(args, id)
	q := "UPDATE {{.Entity.Table}} SET " + strings.Join(sets, ", ") + fmt.Sprintf(" WHERE {{.Entity.PrimaryKey.Name}} = $%d RETURNING {{.AllCols}}", len(args))
	row := r.db.QueryRow(ctx, q, args...)
	var out {{goName .Entity.Name}}
	if err := row.Scan({{ range $i, $f := .Entity.Fields }}{{ if $i }}, {{ end }}&out.{{goName $f.Name}}{{- end }}); err != nil {
		return nil, fmt.Errorf("update {{.Entity.Name}}: %w", err)
	}
	return &out, nil
}
{{ end }}

{{ if hasDelete .Entity.CRUD }}
// Delete removes (or soft-deletes) a {{.Entity.Name}}.
func (r *{{goName .Entity.Name}}Repository) Delete(ctx context.Context, id string) error {
{{- if .Entity.SoftDelete }}
	return r.db.Exec(ctx, ` + "`UPDATE {{.Entity.Table}} SET deleted_at = now() WHERE {{.Entity.PrimaryKey.Name}} = $1`" + `, id)
{{- else }}
	return r.db.Exec(ctx, ` + "`DELETE FROM {{.Entity.Table}} WHERE {{.Entity.PrimaryKey.Name}} = $1`" + `, id)
{{- end }}
}
{{ end }}
`

const handlerTmpl = `package {{.Pkg}}

import (
	"errors"
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/vibeguard/platform/events"
)

// {{goName .Entity.Name}}Handler is the thin HTTP layer over
// {{goName .Entity.Name}}Repository. Verbs are gated by the declaration's
// crud.* booleans — only enabled verbs are emitted, and the route registrar
// only registers the corresponding routes (defense in depth).
type {{goName .Entity.Name}}Handler struct {
	repo *{{goName .Entity.Name}}Repository
	bus  events.Publisher
}

// New{{goName .Entity.Name}}Handler constructs a handler.
func New{{goName .Entity.Name}}Handler(repo *{{goName .Entity.Name}}Repository, bus events.Publisher) *{{goName .Entity.Name}}Handler {
	return &{{goName .Entity.Name}}Handler{repo: repo, bus: bus}
}

{{ if hasCreate .Entity.CRUD }}
// Create handles POST {{.Entity.API.BasePath}}.
func (h *{{goName .Entity.Name}}Handler) Create(c *gin.Context) {
	var req {{goName .Entity.Name}}CreateRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	out, err := h.repo.Create(c.Request.Context(), req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusCreated, out)
}
{{ end }}

{{ if hasRead .Entity.CRUD }}
// Get handles GET {{.Entity.API.BasePath}}/:id.
func (h *{{goName .Entity.Name}}Handler) Get(c *gin.Context) {
	out, err := h.repo.Get(c.Request.Context(), c.Param("id"))
	if errors.Is(err, ErrNotFound) {
		c.JSON(http.StatusNotFound, gin.H{"error": "not found"})
		return
	}
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, out)
}
{{ end }}

{{ if hasList .Entity.CRUD }}
// List handles GET {{.Entity.API.BasePath}}.
func (h *{{goName .Entity.Name}}Handler) List(c *gin.Context) {
	out, err := h.repo.List(c.Request.Context(), 100)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, out)
}
{{ end }}

{{ if hasUpdate .Entity.CRUD }}
// Update handles PATCH {{.Entity.API.BasePath}}/:id.
func (h *{{goName .Entity.Name}}Handler) Update(c *gin.Context) {
	var req {{goName .Entity.Name}}UpdateRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	out, err := h.repo.Update(c.Request.Context(), c.Param("id"), req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, out)
}
{{ end }}

{{ if hasDelete .Entity.CRUD }}
// Delete handles DELETE {{.Entity.API.BasePath}}/:id.
func (h *{{goName .Entity.Name}}Handler) Delete(c *gin.Context) {
	if err := h.repo.Delete(c.Request.Context(), c.Param("id")); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.Status(http.StatusNoContent)
}
{{ end }}

// Register{{goName .Entity.Name}}Routes registers exactly the routes the
// declaration enabled. Verbs not enabled are not registered — clients
// receive a 404 even before reaching handler code.
func Register{{goName .Entity.Name}}Routes(r gin.IRouter, h *{{goName .Entity.Name}}Handler) {
	g := r.Group("{{.Entity.API.BasePath}}")
{{- if hasCreate .Entity.CRUD }}
	g.POST("", h.Create)
{{- end }}
{{- if hasList .Entity.CRUD }}
	g.GET("", h.List)
{{- end }}
{{- if hasRead .Entity.CRUD }}
	g.GET("/:id", h.Get)
{{- end }}
{{- if hasUpdate .Entity.CRUD }}
	g.PATCH("/:id", h.Update)
{{- end }}
{{- if hasDelete .Entity.CRUD }}
	g.DELETE("/:id", h.Delete)
{{- end }}
}
`
