package nextjs

import (
	"strings"
	"testing"

	"github.com/vibeguard/vibeguard/internal/ir"
)

func sampleApp() *ir.Application {
	team := &ir.Entity{
		Name:  "Team",
		Table: "teams",
		Fields: []*ir.Field{
			{Name: "id", Type: ir.FieldUUID, Primary: true},
			{Name: "name", Type: ir.FieldString},
		},
		API: ir.API{BasePath: "/api/v1/teams"},
		CRUD: ir.CRUD{Create: true, Read: true, List: true},
	}
	team.PrimaryKey = team.Fields[0]

	// Task is nested under Team with no explicit base path so the derived
	// nested URL exercises the route helper.
	task := &ir.Entity{
		Name:    "Task",
		Table:   "tasks",
		Fields:  []*ir.Field{{Name: "id", Type: ir.FieldUUID, Primary: true}, {Name: "title", Type: ir.FieldString}},
		Parents: []string{"Team"},
		ParentRefs: []*ir.Entity{team},
		CRUD:    ir.CRUD{Create: true, Read: true, List: true},
	}
	task.PrimaryKey = task.Fields[0]

	mod := ir.Module{Name: "demo", Type: ir.ModuleBusiness, Entities: []*ir.Entity{team, task}}
	team.Module = &mod
	task.Module = &mod
	return &ir.Application{
		APIVersion: "vibeguard.dev/v1",
		Kind:       "Application",
		Metadata:   ir.Metadata{Name: "demo", Version: "1.0.0"},
		Modules:    []ir.Module{mod},
	}
}

func TestNextjsRouteRespectsTree(t *testing.T) {
	app := sampleApp()
	team := app.Modules[0].Entities[0]
	task := app.Modules[0].Entities[1]
	if got := nextjsRoute(team); got != "teams" {
		t.Errorf("team route: got %q want teams", got)
	}
	if got := nextjsRoute(task); got != "teams/[team_id]/tasks" {
		t.Errorf("task route: got %q want teams/[team_id]/tasks", got)
	}
}

func TestPlanProducesExpectedPaths(t *testing.T) {
	app := sampleApp()
	files, err := New().Plan(app)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	want := []string{
		"web/package.json",
		"web/lib/api.ts",
		"web/lib/types.ts",
		"web/app/admin/teams/page.tsx",
		"web/app/admin/teams/[id]/page.tsx",
		"web/app/admin/teams/new/page.tsx",
		"web/app/admin/teams/[team_id]/tasks/page.tsx",
		"web/app/admin/teams/[team_id]/tasks/[id]/page.tsx",
		"web/app/admin/teams/[team_id]/tasks/new/page.tsx",
	}
	got := map[string]bool{}
	for _, f := range files {
		got[f.Path] = true
	}
	for _, w := range want {
		if !got[w] {
			t.Errorf("missing path %q in plan", w)
		}
	}
}

func TestPagesContainEntityName(t *testing.T) {
	app := sampleApp()
	files, err := New().Plan(app)
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		if !strings.HasPrefix(f.Path, "web/app/admin/") || !strings.HasSuffix(f.Path, "page.tsx") {
			continue
		}
		if !strings.Contains(string(f.Content), "Generated by vibeguard") {
			t.Errorf("%s missing generation banner", f.Path)
		}
	}
}

func TestStaticFilesAreKeepIfExists(t *testing.T) {
	app := sampleApp()
	files, _ := New().Plan(app)
	staticPaths := map[string]bool{
		"web/package.json":         true,
		"web/tsconfig.json":        true,
		"web/next.config.mjs":      true,
		"web/tailwind.config.ts":   true,
		"web/postcss.config.mjs":   true,
		"web/.gitignore":           true,
		"web/.env.local.example":   true,
		"web/app/globals.css":      true,
		"web/app/layout.tsx":       true,
	}
	for _, f := range files {
		if staticPaths[f.Path] && !f.KeepIfExists {
			t.Errorf("%s should be KeepIfExists", f.Path)
		}
	}
}
