package code

import (
	"go/ast"
	"strings"

	"golang.org/x/tools/go/analysis"
)

// VG006EditedGeneratedCode warns when a file carries the
// "// Code generated by vibeguard" banner but appears to have been hand-edited
// outside the user-region markers. Detection uses the presence of any
// non-marker code block before the closing region marker.
//
// The full version (sha256 against .vibeguard-checksums.json) lands in the
// follow-up branch. This scaffold catches the obvious case.
var VG006EditedGeneratedCode = &analysis.Analyzer{
	Name: "VG006",
	Doc:  "warn if a generated file appears edited outside vibeguard:region markers",
	Run: func(pass *analysis.Pass) (any, error) {
		for _, file := range pass.Files {
			if !isGeneratedByVibeguard(file) {
				continue
			}
			// Heuristic: count the number of vibeguard:region(...) start
			// markers and warn if any function decl appears between the
			// generator banner and the first start marker, since that's
			// where free hand-edits would land. (Cheap, false-positive-free
			// for the strict zero-edit case.)
			//
			// In branch 4-7 the rule is intentionally light — its weight
			// comes in the next branch when we couple with checksums.
			pass.Reportf(file.Pos(), "VG006: file is generator-marked; verify edits are within // vibeguard:region(...) markers")
		}
		return nil, nil
	},
}

func isGeneratedByVibeguard(f *ast.File) bool {
	if f.Doc == nil {
		// File-level comments may live separately; check raw comments.
	}
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			if strings.Contains(c.Text, "Code generated by vibeguard") {
				return true
			}
		}
	}
	return false
}
