// Package render is the multi-target code-generation engine.
//
// Each Backend is a pure function: IR in, []FileSpec out. The Engine then
// either writes the files atomically, prints a unified diff, or returns
// them in memory for tests. Backends never touch the filesystem directly —
// that separation is what makes golden-file tests possible.
package render

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"

	"github.com/vibeguard/vibeguard/internal/ir"
)

// Backend produces a FileSet from an IR Application.
type Backend interface {
	Name() string
	Plan(app *ir.Application) (FileSet, error)
}

// FileSet is an ordered slice of FileSpecs. Order matters for deterministic
// diffing.
type FileSet []FileSpec

// FileSpec is one file the generator wants on disk.
type FileSpec struct {
	Path    string      // relative to Engine.Root
	Mode    os.FileMode // typically 0644 or 0755
	Content []byte
	Header  string // "// Code generated by vibeguard; DO NOT EDIT." prepended (if non-empty)

	// KeepIfExists makes Mode=ModeWrite skip this file when the path already
	// exists. Used for developer-owned files (e.g. business-logic node stubs)
	// that the generator scaffolds once and the developer fills in.
	KeepIfExists bool
}

// Mode controls what Engine.Run does with the planned files.
type Mode int

const (
	ModeWrite Mode = iota
	ModeDryRun
	ModeDiff
)

// Engine drives a list of Backends.
type Engine struct {
	Root     string
	Backends []Backend
	Mode     Mode
	Out      io.Writer
}

// Report is the result of an Engine.Run.
type Report struct {
	Backends     []BackendReport
	FilesWritten []string
	Skipped      []string
}

// BackendReport summarises one backend's contribution.
type BackendReport struct {
	Name      string
	NumFiles  int
	NumBytes  int
	Diagnostic string
}

// Run executes every backend and applies the requested mode.
func (e *Engine) Run(app *ir.Application) (*Report, error) {
	if e.Out == nil {
		e.Out = os.Stdout
	}
	report := &Report{}
	for _, b := range e.Backends {
		fs, err := b.Plan(app)
		if err != nil {
			return report, fmt.Errorf("%s backend: %w", b.Name(), err)
		}
		sort.SliceStable(fs, func(i, j int) bool { return fs[i].Path < fs[j].Path })
		br := BackendReport{Name: b.Name(), NumFiles: len(fs)}
		for _, fileSpec := range fs {
			br.NumBytes += len(fileSpec.Content)
			content := fileSpec.Content
			if fileSpec.Header != "" {
				content = append([]byte(fileSpec.Header+"\n\n"), content...)
			}
			fullPath := filepath.Join(e.Root, fileSpec.Path)
			switch e.Mode {
			case ModeWrite:
				if fileSpec.KeepIfExists {
					if _, err := os.Stat(fullPath); err == nil {
						report.Skipped = append(report.Skipped, fileSpec.Path)
						continue
					}
				}
				if err := writeFile(fullPath, fileSpec.Mode, content); err != nil {
					return report, fmt.Errorf("write %s: %w", fileSpec.Path, err)
				}
				report.FilesWritten = append(report.FilesWritten, fileSpec.Path)
			case ModeDryRun:
				fmt.Fprintf(e.Out, "would write %s (%d bytes)\n", fileSpec.Path, len(content))
			case ModeDiff:
				if err := printDiff(e.Out, fullPath, content); err != nil {
					return report, fmt.Errorf("diff %s: %w", fileSpec.Path, err)
				}
			}
		}
		report.Backends = append(report.Backends, br)
	}
	return report, nil
}

func writeFile(path string, mode os.FileMode, content []byte) error {
	if mode == 0 {
		mode = 0o644
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, content, mode); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func printDiff(out io.Writer, path string, want []byte) error {
	have, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if string(have) == string(want) {
		fmt.Fprintf(out, "= %s\n", path)
		return nil
	}
	fmt.Fprintf(out, "≠ %s (%d → %d bytes)\n", path, len(have), len(want))
	return nil
}
